AWSTemplateFormatVersion: 2010-09-09
# This CloudFormation template for fake VPC
Parameters:
  VPCRange:
    Type: 'AWS::EC2::VPC::Id'
  PubSubnetA:
    Type: 'AWS::EC2::Subnet::Id'
  PubSubnetB:
    Type: 'AWS::EC2::Subnet::Id'
Conditions:
  Never:
    !Equals [ "A", "B" ]
Resources:
  NonResource:
    Type: Custom::NonResource
    Condition: Never
Outputs:
  VpcId:
    Description: VPCId of newly created VPC
    Value: !Ref VPCRange
    Export:
      Name: "VpcId"
  SubnetA:
    Description: Public SubnetA Id of newly created Subnet
    Value: !Ref PubSubnetA
    Export: 
      Name: "SubnetA"
  SubnetB:
    Description: Public SubnetB Id of newly created Subnet
    Value: !Ref PubSubnetB
    Export: 
      Name: "SubnetB"